### ISSUE TITLE
OBJ 2: Event Invite Functionality

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/planning#5]
## Action Item
Deploy event invite functionality so that users can invite other users on Carpe to an event.

## Why?
Events are (more often than not) between multiple people. Carpe users need the ability to invite other users to their events so that Carpe can replace a competitor’s scheduler.

## Key Result
Event invite functionality deployed with the ability for users to invite others, get notifications on event updates, and respond with yes/no/maybe to an event invite.

**Comment by vkoves** [comment]
Closing all old planning issues to clean house
