### ISSUE TITLE
OBJ 2: Group Functionality

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/planning#6]
## Action Item
Deploy basic group functionality to allow multiple users to plan events on Carpe

## Why?
Events are often coordinated by groups of people who have a shared interest or are in an organization together. Being able to create events and have a group calendar will make Carpe more useful to users.

## Key Result
Group functionality deployed with the ability for a user to view a group’s schedule and to view events they join on their dashboard and their schedule.

**Comment by vkoves** [comment]
Closing all old planning issues to clean house
