### ISSUE TITLE
OBJ 2: Optimize Dashboard (Signed In)

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/planning#7]
## Action Item
Optimize the dashboard (signed in homepage) to be more usable.

## Why?
The dashboard is the first place on Carpe where you can see what other users are up to, and loading it quickly is critical to allowing users to jump into Carpe and start viewing other users’ schedules.

## Key Result
Have the dashboard’s initial page load < 1 sec, and total page load < 2 sec on a complex account like Viktor’s.

**Comment by vkoves** [comment]
Started working on this last week, with work on `carpe:optimize-dashboard`

**Comment by vkoves** [comment]
Closing all old planning issues to clean house
